### ISSUE TITLE
distribute a wheel to pypi

### ISSUE THREAD

**Issue by drmaples** [freach/udatetime#13]
Please distribute a wheel to pypi instead of an egg or "dumb" binary

![image](https://cloud.githubusercontent.com/assets/165819/18328478/99c051ce-7514-11e6-8467-deefa1730d0a.png)

**Comment by freach** [comment]
The distribution of binary wheels with C extensions for Linux is currently not supported by PyPI. Please see [https://github.com/pypa/pypi-legacy/issues/120](https://github.com/pypa/pypi-legacy/issues/120). Only MacOS X and Windows are supported. udatetime is untested on Windows and likely to be incompatible due to the use of POSIX only features in udatetime. For a MacOS X build I would need a Mac system, which I don't have access to.
A universal wheel can't be used due to the C extension in udatetime.
